### ISSUE TITLE
How to hide or disable the default template?

### ISSUE THREAD

**Issue by kwhsiung** [arnedesmedt/vue-ads-pagination#11]
Thanks for creating this useful component, but I have question about [default template](https://github.com/arnedesmedt/vue-ads-pagination#default).

Is there any way we can hide or disable default template from showing? I just want the pagination buttons.

It seems if we didn't provide a blank default template, the default template will always showing a string like `1 - 10 of 200 items`.

Here is the [jsbin](https://jsfiddle.net/yr7ghkxm/) that forked from your demo, I just simply add a simple blank default template `<template slot-scope="props"><div></div></template>`, thats all I got to figuring out the way to hide the default template.

**Comment by arnedesmedt** [comment]
And that's the right way to hide the default template. There is currently no boolean property to hide that template. But I don't think it's necessary if you can hide it by overwriting the template.

Let me know if you got a founded argument to change this behaviour.
