### ISSUE TITLE
Error: page may be maximum the total number of pages minus one

### ISSUE THREAD

**Issue by kawoki** [arnedesmedt/vue-ads-pagination#14]
After adding page value to zero, the error shows up.

![image](https://user-images.githubusercontent.com/12818739/60675984-4c1e5600-9eb0-11e9-987b-507ddcc2b454.png)

**Comment by arnedesmedt** [comment]
What is your total amount of items? If this is 0 the error was thrown. I now changed it in version 2.1.5. If your page is 0 and the total-items is 0, the error is not thrown anymore.

**Comment by kawoki** [comment]
Thank you :)
