### ISSUE TITLE
Page number doesn't follow if totalItems is decreased.

### ISSUE THREAD

**Issue by pavelav** [arnedesmedt/vue-ads-pagination#16]
*Steps to reproduce*:
1. Start the default demo app: 12 rows, 2 pages (10 items per page).
2. Navigate to the second page.
3. Open browser Vue dev tools and on the App component change `totalItems` to 10. This is equivalent to deleting all rows on the page in a real app.

*Expected result*:
The page number should have been reduced by 1, so I could see the first 10 rows.

*Actual result*:
Page buttons are gone, but I'm still on page 2 seeing nothing. The text is:
> 11 - 10 of 10 items

*Impact*:
Can't use the table after the issue is encountered.

The attached screen recording illustrates the issue.
[page-not-decreased.zip](https://github.com/arnedesmedt/vue-ads-pagination/files/3585678/page-not-decreased.zip) (360 kB)
// I wasn't able to attach a video directly, so had to pack it into a supported container.

**Comment by pavelav** [comment]
A similar issue is with `itemsPerPage`.
*Steps to reproduce*:
1 and 2 - same as above.
3. ... change `itemsPerPage` to 2 to get more pages.
4. navigate to page *n* (say 3).
5. Change `itemsPerPage` to 20, so all rows fit on one page.

*Expected result*:
The page number should have been set to 1 (0 internally), so I could see the existing rows.

*Actual result*:
Page buttons are gone, but I'm still on page 3 seeing nothing. The text is:
> 41 - 12 of 12 items

**Comment by arnedesmedt** [comment]
Thx for pointing the problem.
